#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  packageios:
    name: Build and Test Swift Package iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziLocation
      artifactname: SpeziLocation.xcresult
  packagewatchos:
    name: Build and Test Swift Package watchOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziLocation
      resultBundle: SpeziLocationWatchOS.xcresult
      destination: 'platform=watchOS Simulator,name=Apple Watch Series 8 (45mm)'
      artifactname: SpeziLocationWatchOS.xcresult
  ios:
    name: Build and Test iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      path: 'Tests/UITests'
      scheme: TestApp
      artifactname: TestApp.xcresult
  ipados:
    name: Build and Test iPadOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      path: 'Tests/UITests'
      scheme: TestApp
      resultBundle: TestAppiPadOS.xcresult
      destination: 'platform=iOS Simulator,name=iPad mini (6th generation)'
      artifactname: TestAppiPadOS.xcresult
  codeql:
    name: CodeQL
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      codeql: true
      xcodeversion: '14.3.1'
      scheme: SpeziLocation
    permissions:
      security-events: write
      actions: read
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [packageios, packagewatchos, ios, ipados]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: SpeziLocation.xcresult SpeziLocationWatchOS.xcresult SpeziLocationVisionOS.xcresult TestApp.xcresult TestAppiPadOS.xcresult TestAppWatchApp.xcresult
